# Generated by Django 3.1.7 on 2021-04-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
