# Generated by Django 3.1.7 on 2021-03-25 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registerform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='area',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Rural', max_length=50),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='membercategory',
            field=models.CharField(choices=[('Ordinary', 'Ordinary'), ('Temple Manager', 'Temple Manager'), ('Prohits', 'Prohits')], default='Ordinary', max_length=50),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='membertype',
            field=models.CharField(choices=[('Life Member', 'Life Member'), ('Active Member', 'Active Member'), ('General Member', 'General Member')], default='General Member', max_length=50),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='templename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='village',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
