# Generated by Django 3.1.7 on 2021-03-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerform', '0002_auto_20210325_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='code',
            field=models.CharField(default='notgiven', max_length=20),
        ),
    ]
